export const ORDER_STATUS = {
    PENDING_REVIEW: "Pending Review",
    VERIFICATION_REQUIRED: "Verification Required",
    ORDER_CONFIRMATION_SENT: "Order Confirmation Sent",
    ORDER_APPROVED: "Order Approved",
    CUSTOMER_CONFIRMED: "Customer Confirmed",
    CUSTOMER_CANCELLED: "Customer Cancelled",
    ORDER_PAID: "Order Paid",
    ORDER_REJECTED: "Order Rejected",
    DELIVERING: "Delivering",
    COMPLETED: "Completed",
    CUSTOMER_UNREACHABLE: "Customer Unreachable",
    RETURNED: "Returned",
    EXCHANGED: "Exchanged",
};
