import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShieldCheck, Cpu, LineChart, Handshake } from "lucide-react";
export const About = () => {
    return (_jsxs("section", { id: "about", className: "relative pt-16 pb-20 md:pt-20 md:pb-24 text-gray-200 overflow-hidden scroll-mt-24", style: {
            background: 'linear-gradient(to bottom right, #0B0F28 0%, #232a6b 25%, #3184b1 75%, #4B3087 100%)',
        }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-[#0B0F28]/40 via-transparent to-transparent z-0 pointer-events-none" }), _jsx("div", { className: "absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-5 z-0 pointer-events-none" }), _jsxs("div", { className: "relative z-10 max-w-7xl mx-auto px-6", children: [_jsxs("div", { className: "text-center max-w-4xl mx-auto mb-20", children: [_jsx("h2", { className: "text-5xl md:text-6xl font-bold mb-8 gradient-text", children: "About CodFence" }), _jsxs("p", { className: "text-lg text-[#E5E7EB]/70 leading-relaxed text-left max-w-5xl mx-auto", children: ["CodFence is an intelligent verification and protection platform designed to make every Cash-on-Delivery (COD) transaction secure, seamless, and growth-driven. In markets where COD remains a key payment method yet highly vulnerable to cancellations and fraud, CodFence empowers eCommerce merchants to turn operational risks into opportunities for trust and conversion.", _jsx("br", {}), _jsx("br", {}), "By leveraging AI-powered risk scoring and automated customer engagement, CodFence helps merchants confirm orders instantly, prevent losses, and enhance delivery success \u2014 all while improving customer experience and retention. It\u2019s not just about preventing fraud; it\u2019s about building a smarter, more reliable path to sales growth."] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-10 mb-28", children: [_jsxs("div", { className: "glass-card p-8 lg:p-10 text-left hover:translate-y-[-4px]", children: [_jsx("h3", { className: "text-3xl font-semibold text-[#E5E7EB] mb-4", children: "Mission" }), _jsx("p", { className: "text-[#E5E7EB]/70 leading-relaxed", children: "Empower merchants to transform complex COD operations into secure, simple, and trustworthy transactions." })] }), _jsxs("div", { className: "glass-card p-8 lg:p-10 text-left hover:translate-y-[-4px]", children: [_jsx("h3", { className: "text-3xl font-semibold text-[#E5E7EB] mb-4", children: "Vision" }), _jsx("p", { className: "text-[#E5E7EB]/70 leading-relaxed", children: "Become Southeast Asia's leading intelligent verification and protection solution for eCommerce." })] })] }), _jsxs("div", { id: "core-values", className: "text-center mb-20 scroll-mt-24", children: [_jsx("h3", { className: "text-4xl font-bold mb-14 gradient-text", children: "Core Values" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8", children: [
                                    {
                                        icon: _jsx(ShieldCheck, { className: "w-10 h-10 text-cyan-400 mb-3" }),
                                        title: "Trust & Efficiency",
                                        text: "Every transaction secured, every process optimized.",
                                    },
                                    {
                                        icon: _jsx(Cpu, { className: "w-10 h-10 text-purple-400 mb-3" }),
                                        title: "Innovation",
                                        text: "Leveraging AI and automation for smarter risk prevention.",
                                    },
                                    {
                                        icon: _jsx(Handshake, { className: "w-10 h-10 text-blue-400 mb-3" }),
                                        title: "Reliability",
                                        text: "Helping merchants grow with confidence and control.",
                                    },
                                    {
                                        icon: _jsx(LineChart, { className: "w-10 h-10 text-emerald-400 mb-3" }),
                                        title: "Scalability",
                                        text: "Building a secure foundation for long-term growth.",
                                    },
                                ].map((v, i) => (_jsxs("div", { className: "glass-card p-6 lg:p-8 hover:translate-y-[-4px] flex flex-col items-center text-center", children: [v.icon, _jsx("h4", { className: "text-lg lg:text-xl font-semibold text-[#E5E7EB] mb-2 mt-2", children: v.title }), _jsx("p", { className: "text-[#E5E7EB]/70 text-sm leading-relaxed", children: v.text })] }, i))) })] }), _jsxs("div", { id: "technology", className: "max-w-4xl mx-auto text-left mb-16 scroll-mt-24", children: [_jsx("h3", { className: "text-4xl font-bold mb-10 gradient-text text-center", children: "Technology & Offerings" }), _jsxs("ul", { className: "space-y-5 text-[#E5E7EB]/70 leading-relaxed", children: [_jsxs("li", { children: [_jsx("span", { className: "text-white font-semibold", children: "FenceAI:" }), " AI-driven risk scoring engine that learns from transaction data."] }), _jsxs("li", { children: [_jsx("span", { className: "text-white font-semibold", children: "FenceBot:" }), " Automated order confirmation via Zalo OA or Messenger."] }), _jsxs("li", { children: [_jsx("span", { className: "text-white font-semibold", children: "FencePay:" }), " Optional module for QR and prepaid payment integrations."] }), _jsxs("li", { children: [_jsx("span", { className: "text-white font-semibold", children: "FenceHub:" }), " Centralized dashboard for COD data management and analytics."] })] })] }), _jsxs("div", { className: "mt-24 max-w-5xl mx-auto text-center px-6", children: [_jsx("div", { className: "h-[1px] w-32 mx-auto mb-8 bg-gradient-to-r from-[#6366F1] via-[#7C3AED] to-[#8B5CF6] opacity-50" }), _jsx("p", { className: "text-2xl italic font-light text-[#E5E7EB]/80 leading-relaxed tracking-wide", children: "\u201CCodFence enables eCommerce merchants to protect and optimize every COD transaction through intelligent verification, automation, and data-driven insights. We believe that when verification becomes seamless, protection becomes powerful \u2014 and protection, in turn, becomes growth.\u201D" })] })] })] }));
};
